import { ScheduleAssignment, ScheduleSong, WorshipSchedule } from '../models/Schedule';
import { ServiceTypeValue, serviceTypes } from '../constants/serviceTypes';
import { LeaderSong, WorkerRole } from '../models/Worker';
import { api, getApiBaseUrl } from './api';

const roleLabels = [
  ['leader', 'Leader'],
  ['backup1', 'Backup'],
  ['backup2', 'Backup'],
  ['acoustic', 'Acoustic'],
  ['electric', 'Electric'],
  ['keyboard', 'Keyboard'],
  ['bass', 'Bass'],
  ['drums', 'Drums'],
  ['beatbox', 'Beatbox'],
] as const;

export interface SaveSchedulePayload {
  date: string;
  service_type: ServiceTypeValue;
  assignments: Array<{
    role: string;
    worker_id: string;
  }>;
  songs?: ScheduleSong[];
  lineup?: string;
  notes?: string;
}

export type UpdateSchedulePayload = Partial<SaveSchedulePayload>;

export interface AutoGenerationPreviewPayload {
  year: number;
  month: number;
  service_type?: ServiceTypeValue;
  includeOptionalRoles?: boolean;
  allowYouthBackupFallback?: boolean;
}

export type AutoGenerationPreviewStatus = 'generated' | 'skipped' | 'needs_attention';

export interface AutoGeneratedScheduleRow {
  date: string;
  service_type: ServiceTypeValue;
  status: AutoGenerationPreviewStatus;
  assignments: Array<{
    role: string;
    worker_id: string;
    worker_name: string;
  }>;
  warnings: string[];
}

export interface AutoGenerationPreview {
  year: number;
  month: number;
  service_type: ServiceTypeValue;
  rows: AutoGeneratedScheduleRow[];
}

export interface AutoGenerationConfirmPayload {
  schedules: Array<{
    date: string;
    service_type: ServiceTypeValue;
    assignments: Array<{
      role: string;
      worker_id: string;
    }>;
    songs?: ScheduleSong[];
    lineup?: string;
    notes?: string;
  }>;
}

export interface MyAssignmentsResult {
  worker: {
    id: string;
    name: string;
    roles: WorkerRole[];
    leaderSongs: LeaderSong[];
  } | null;
  items: WorshipSchedule[];
}

export const fetchSchedules = async (): Promise<WorshipSchedule[]> => {
  try {
    const response = await api.get('/schedules');
    return normalizeScheduleResponse(response.data);
  } catch (error) {
    const response = await api.get(`${getApiBaseUrl()}/schedule/`);
    return normalizeScheduleResponse(response.data);
  }
};

export const fetchMyAssignments = async (): Promise<MyAssignmentsResult> => {
  const response = await api.get('/schedules/my-assignments');
  const data = response.data.data;
  const worker = isRecord(data?.worker) ? data.worker : null;

  return {
    worker: worker
      ? {
          id: getString(worker, '_id') ?? '',
          name: getString(worker, 'name') ?? '',
          roles: normalizeWorkerRoles(getArray(worker, 'roles')),
          leaderSongs: normalizeLeaderSongs(getArray(worker, 'leader_songs')),
        }
      : null,
    items: normalizeScheduleResponse(data?.items ?? []),
  };
};

export const updateScheduleLineup = async (
  id: string,
  lineup: string,
): Promise<WorshipSchedule> => {
  const response = await api.patch(`/schedules/${id}/lineup`, { lineup });
  return normalizeRequiredSchedule(response.data.data);
};

export const fetchScheduleById = async (id: string): Promise<WorshipSchedule> => {
  const response = await api.get(`/schedules/${id}`);
  return normalizeRequiredSchedule(response.data.data);
};

export const createSchedule = async (
  payload: SaveSchedulePayload,
): Promise<WorshipSchedule> => {
  const response = await api.post('/schedules', payload);
  return normalizeRequiredSchedule(response.data.data);
};

export const updateSchedule = async (
  id: string,
  payload: UpdateSchedulePayload,
): Promise<WorshipSchedule> => {
  const response = await api.patch(`/schedules/${id}`, payload);
  return normalizeRequiredSchedule(response.data.data);
};

export const deleteSchedule = async (id: string): Promise<void> => {
  await api.delete(`/schedules/${id}`);
};

export const previewAutoGeneration = async (
  payload: AutoGenerationPreviewPayload,
): Promise<AutoGenerationPreview> => {
  const response = await api.post('/schedules/auto-generation/preview', payload);
  return (response.data.data ?? response.data) as AutoGenerationPreview;
};

export const confirmAutoGeneration = async (
  payload: AutoGenerationConfirmPayload,
): Promise<WorshipSchedule[]> => {
  const response = await api.post('/schedules/auto-generation/confirm', payload);
  return normalizeScheduleResponse(response.data);
};

export const normalizeScheduleResponse = (payload: unknown): WorshipSchedule[] => {
  const rawData = isRecord(payload) && 'data' in payload ? payload.data : payload;
  const items = Array.isArray(rawData)
    ? rawData
    : isRecord(rawData) && Array.isArray(rawData.items)
      ? rawData.items
      : [];

  return items
    .map(normalizeSchedule)
    .filter(Boolean)
    .sort((a: WorshipSchedule, b: WorshipSchedule) => {
      return new Date(a.date).getTime() - new Date(b.date).getTime();
    });
};

const normalizeSchedule = (item: unknown): WorshipSchedule | null => {
  if (!isRecord(item)) {
    return null;
  }

  const date = getString(item, 'date') ?? getString(item, 'date_time');

  if (!date) {
    return null;
  }

  const id = getString(item, '_id') ?? getString(item, 'id') ?? date;

  return {
    id,
    date: toDateInputValue(date),
    serviceType: normalizeServiceType(
      getString(item, 'service_type') ?? getString(item, 'serviceType'),
    ),
    status: getString(item, 'status') ?? 'active',
    assignments: normalizeAssignments(item),
    songs: normalizeSongs(getArray(item, 'songs') ?? getArray(item, 'line_up')),
    lineup:
      getString(item, 'lineup') ??
      getString(item, 'line_up_url') ??
      getString(item, 'line_up'),
    notes: getString(item, 'notes'),
  };
};

const normalizeServiceType = (value?: string): ServiceTypeValue => {
  return serviceTypes.some((serviceType) => serviceType.value === value)
    ? (value as ServiceTypeValue)
    : 'main';
};

const normalizeRequiredSchedule = (item: unknown): WorshipSchedule => {
  const schedule = normalizeSchedule(item);

  if (!schedule) {
    throw new Error('Schedule response could not be normalized');
  }

  return schedule;
};

const normalizeAssignments = (item: Record<string, unknown>): ScheduleAssignment[] => {
  const assignments = getArray(item, 'assignments');

  if (assignments) {
    return assignments.filter(isRecord).map((assignment) => ({
      role: getString(assignment, 'role') ?? '',
      workerId: getString(assignment, 'worker_id') ?? getString(assignment, 'workerId'),
      workerName: getString(assignment, 'worker_name') ?? getString(assignment, 'workerName') ?? '',
    }));
  }

  const workers = getArray(item, 'workers');

  if (workers) {
    return workers.filter(isRecord).map((worker) => ({
      role: getString(worker, 'role') ?? '',
      workerId: getString(worker, 'worker_id') ?? getString(worker, 'workerId'),
      workerName:
        getString(worker, 'name') ??
        getString(worker, 'worker_name') ??
        getString(worker, 'workerName') ??
        '',
    }));
  }

  return roleLabels
    .map(([key, role]) => ({
      role,
      workerName: getString(item, key),
    }))
    .filter((assignment) => Boolean(assignment.workerName));
};

const normalizeSongs = (songs?: unknown[]): ScheduleSong[] => {
  if (!songs) {
    return [];
  }

  return songs
    .map((song) => {
      if (typeof song === 'string') {
        return { title: song };
      }

      if (!isRecord(song)) {
        return null;
      }

      const title = getString(song, 'title') ?? getString(song, 'name');

      if (!title) {
        return null;
      }

      return {
        title,
        key: getString(song, 'key'),
      };
    })
    .filter((song): song is ScheduleSong => Boolean(song));
};

const normalizeWorkerRoles = (roles?: unknown[]): WorkerRole[] => {
  const validRoles: WorkerRole[] = [
    'Leader',
    'Backup',
    'Acoustic',
    'Bass',
    'Drums',
    'Beatbox',
    'Keyboard',
    'Electric',
  ];

  return (roles ?? []).filter(
    (role): role is WorkerRole => typeof role === 'string' && validRoles.includes(role as WorkerRole),
  );
};

const normalizeLeaderSongs = (songs?: unknown[]): LeaderSong[] => {
  return (songs ?? [])
    .filter(isRecord)
    .map((song) => ({
      title: getString(song, 'title') ?? '',
      key: getString(song, 'key') ?? '',
    }))
    .filter((song) => song.title && song.key);
};

const toDateInputValue = (value: string | Date) => {
  if (typeof value === 'string') {
    const dateOnlyMatch = value.match(/^(\d{4})-(\d{2})-(\d{2})/);

    if (dateOnlyMatch) {
      return dateOnlyMatch[0];
    }
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return String(value);
  }

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;
};

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null;
};

const getString = (record: Record<string, unknown>, key: string) => {
  const value = record[key];
  return typeof value === 'string' ? value : undefined;
};

const getArray = (record: Record<string, unknown>, key: string) => {
  const value = record[key];
  return Array.isArray(value) ? value : undefined;
};
