import { ScheduleAssignment, ScheduleSong, WorshipSchedule } from '../models/Schedule';
import { ServiceTypeValue } from '../constants/serviceTypes';
import { WorkerRole } from '../models/Worker';
import { api, getApiBaseUrl } from './api';
import axios from 'axios';

const roleLabels = [
  ['leader', 'Leader'],
  ['backup1', 'Backup'],
  ['backup2', 'Backup'],
  ['acoustic', 'Acoustic'],
  ['electric', 'Electric'],
  ['keyboard', 'Keyboard'],
  ['bass', 'Bass'],
  ['drums', 'Drums'],
  ['beatbox', 'Beatbox'],
] as const;

export interface SaveSchedulePayload {
  date: string;
  service_type: ServiceTypeValue;
  assignments: Array<{
    slot_key?: string;
    role: string;
    worker_id: string;
  }>;
  songs?: ScheduleSong[];
  lineup?: string;
  notes?: string;
}

export type UpdateSchedulePayload = Partial<SaveSchedulePayload>;

export interface AutoGenerationPreviewPayload {
  year: number;
  month: number;
  service_type?: ServiceTypeValue;
  service_types?: ServiceTypeValue[];
  worker_pools?: Array<{
    service_type: ServiceTypeValue;
    slot_key: string;
    worker_ids: string[];
  }>;
  includeOptionalRoles?: boolean;
  allowYouthBackupFallback?: boolean;
}

export type AutoGenerationPreviewStatus = 'generated' | 'skipped' | 'needs_attention';

export type ScheduleConflictCode =
  | 'WORKER_ALREADY_ASSIGNED'
  | 'WORKER_UNAVAILABLE'
  | 'DUPLICATE_WORKER_ASSIGNMENT'
  | 'MISSING_REQUIRED_ASSIGNMENT'
  | 'SCHEDULE_ALREADY_EXISTS'
  | 'INVALID_ASSIGNMENT'
  | 'INVALID_SCHEDULE_DATE';

export interface ScheduleConflict {
  code: ScheduleConflictCode;
  date: string;
  message: string;
  worker_id?: string;
  worker_name?: string;
  slot_key?: string;
  slot_label?: string;
  role?: string;
  blocking_schedule?: {
    id: string;
    service_type: string;
    role?: string;
    slot_key?: string;
  };
}

export interface AutoGeneratedScheduleRow {
  date: string;
  service_type: ServiceTypeValue;
  status: AutoGenerationPreviewStatus;
  assignments: Array<{
    role: string;
    slot_key?: string;
    worker_id: string;
    worker_name: string;
  }>;
  warnings: string[];
  save_status?: 'saved';
  conflicts?: ScheduleConflict[];
}

export interface AutoGenerationPreview {
  year: number;
  month: number;
  service_type: ServiceTypeValue;
  service_types?: ServiceTypeValue[];
  rows: AutoGeneratedScheduleRow[];
}

export interface AutoGenerationConfirmPayload {
  schedules: Array<{
    date: string;
    service_type: ServiceTypeValue;
    assignments: Array<{
      role: string;
      slot_key?: string;
      worker_id: string;
    }>;
    songs?: ScheduleSong[];
    lineup?: string;
    notes?: string;
  }>;
}

export interface AutoGenerationConfirmResult {
  items: Array<{
    date: string;
    service_type: ServiceTypeValue;
    status: 'created' | 'failed';
    schedule?: WorshipSchedule;
    message?: string;
    conflicts?: ScheduleConflict[];
  }>;
  summary: {
    submitted: number;
    created: number;
    failed: number;
  };
}

export interface AssignmentConstraint {
  worker_id: string;
  worker_name?: string;
  code: 'WORKER_ALREADY_ASSIGNED' | 'WORKER_UNAVAILABLE';
  message: string;
  blocking_schedule?: {
    id: string;
    service_type: string;
    role?: string;
    slot_key?: string;
  };
}

export interface AssignmentConstraintsResult {
  year: number;
  month: number;
  dates: Array<{
    date: string;
    blocked_workers: AssignmentConstraint[];
  }>;
}

export interface MyAssignmentsResult {
  worker: {
    id: string;
    name: string;
    roles: WorkerRole[];
  } | null;
  items: WorshipSchedule[];
}

export const fetchSchedules = async (): Promise<WorshipSchedule[]> => {
  try {
    const response = await api.get('/schedules');
    return normalizeScheduleResponse(response.data);
  } catch (error) {
    const response = await api.get(`${getApiBaseUrl()}/schedule/`);
    return normalizeScheduleResponse(response.data);
  }
};

export const fetchMyAssignments = async (): Promise<MyAssignmentsResult> => {
  const response = await api.get('/schedules/my-assignments');
  const data = response.data.data;
  const worker = isRecord(data?.worker) ? data.worker : null;

  return {
    worker: worker
      ? {
          id: getString(worker, '_id') ?? '',
          name: getString(worker, 'name') ?? '',
          roles: normalizeWorkerRoles(getArray(worker, 'roles')),
        }
      : null,
    items: normalizeScheduleResponse(data?.items ?? []),
  };
};

export const updateScheduleLineup = async (
  id: string,
  payload: {
    songs: Array<{
      song_id?: string;
      title?: string;
      artist?: string;
      key?: string;
    }>;
    spotify_url?: string;
  },
): Promise<WorshipSchedule> => {
  const response = await api.patch(`/schedules/${id}/lineup`, payload);
  return normalizeRequiredSchedule(response.data.data);
};

export const fetchScheduleById = async (id: string): Promise<WorshipSchedule> => {
  const response = await api.get(`/schedules/${id}`);
  return normalizeRequiredSchedule(response.data.data);
};

export const createSchedule = async (
  payload: SaveSchedulePayload,
): Promise<WorshipSchedule> => {
  const response = await api.post('/schedules', payload);
  return normalizeRequiredSchedule(response.data.data);
};

export const updateSchedule = async (
  id: string,
  payload: UpdateSchedulePayload,
): Promise<WorshipSchedule> => {
  const response = await api.patch(`/schedules/${id}`, payload);
  return normalizeRequiredSchedule(response.data.data);
};

export const deleteSchedule = async (id: string): Promise<void> => {
  await api.delete(`/schedules/${id}`);
};

export const previewAutoGeneration = async (
  payload: AutoGenerationPreviewPayload,
): Promise<AutoGenerationPreview> => {
  const response = await api.post('/schedules/auto-generation/preview', payload);
  return (response.data.data ?? response.data) as AutoGenerationPreview;
};

export const confirmAutoGeneration = async (
  payload: AutoGenerationConfirmPayload,
): Promise<AutoGenerationConfirmResult> => {
  const response = await api.post('/schedules/auto-generation/confirm', payload);
  const data = isRecord(response.data) && isRecord(response.data.data)
    ? response.data.data
    : response.data;
  const result = data as unknown as {
    items?: Array<Record<string, unknown>>;
    summary?: AutoGenerationConfirmResult['summary'];
  };

  return {
    items: (result.items ?? []).map((item) => {
      const schedule = isRecord(item.schedule) ? item.schedule : undefined;
      return {
        date: getString(item, 'date') ?? '',
        service_type:
          getString(item, 'service_type') ??
          (schedule ? getString(schedule, 'serviceType') : undefined) ??
          (schedule ? getString(schedule, 'service_type') : undefined) ??
          'main',
        status: getString(item, 'status') === 'created' ? 'created' as const : 'failed' as const,
        schedule: schedule ? normalizeSchedule(schedule) ?? undefined : undefined,
        message: getString(item, 'message'),
        conflicts: Array.isArray(item.conflicts)
          ? item.conflicts as ScheduleConflict[]
          : undefined,
      };
    }),
    summary: result.summary ?? { submitted: 0, created: 0, failed: 0 },
  };
};

export const fetchAssignmentConstraints = async (
  year: number,
  month: number,
): Promise<AssignmentConstraintsResult> => {
  const response = await api.get('/schedules/assignment-constraints', {
    params: { year, month },
  });
  const data = isRecord(response.data) && isRecord(response.data.data)
    ? response.data.data
    : response.data;
  return data as unknown as AssignmentConstraintsResult;
};

export const getScheduleRequestConflicts = (
  error: unknown,
  date: string,
): ScheduleConflict[] => {
  if (axios.isAxiosError(error)) {
    const conflicts = error.response?.data?.errors?.conflicts;
    if (Array.isArray(conflicts) && conflicts.length) {
      return conflicts as ScheduleConflict[];
    }
    const message = error.response?.data?.message;
    if (typeof message === 'string') {
      return [{ code: 'INVALID_ASSIGNMENT', date, message }];
    }
  }

  return [{
    code: 'INVALID_ASSIGNMENT',
    date,
    message: error instanceof Error ? error.message : 'Schedule could not be saved',
  }];
};

export const normalizeScheduleResponse = (payload: unknown): WorshipSchedule[] => {
  const rawData = isRecord(payload) && 'data' in payload ? payload.data : payload;
  const items = Array.isArray(rawData)
    ? rawData
    : isRecord(rawData) && Array.isArray(rawData.items)
      ? rawData.items
      : [];

  return items
    .map(normalizeSchedule)
    .filter(Boolean)
    .sort((a: WorshipSchedule, b: WorshipSchedule) => {
      return new Date(a.date).getTime() - new Date(b.date).getTime();
    });
};

const normalizeSchedule = (item: unknown): WorshipSchedule | null => {
  if (!isRecord(item)) {
    return null;
  }

  const date = getString(item, 'date') ?? getString(item, 'date_time');

  if (!date) {
    return null;
  }

  const id = getString(item, '_id') ?? getString(item, 'id') ?? date;

  return {
    id,
    date: toDateInputValue(date),
    serviceType:
      getString(item, 'service_type') ??
      getString(item, 'serviceType') ??
      'main',
    status: getString(item, 'status') ?? 'active',
    assignments: normalizeAssignments(item),
    songs: normalizeSongs(getArray(item, 'songs') ?? getArray(item, 'line_up')),
    lineup:
      getString(item, 'lineup') ??
      getString(item, 'line_up_url') ??
      getString(item, 'line_up'),
    notes: getString(item, 'notes'),
  };
};

const normalizeRequiredSchedule = (item: unknown): WorshipSchedule => {
  const schedule = normalizeSchedule(item);

  if (!schedule) {
    throw new Error('Schedule response could not be normalized');
  }

  return schedule;
};

const normalizeAssignments = (item: Record<string, unknown>): ScheduleAssignment[] => {
  const assignments = getArray(item, 'assignments');

  if (assignments) {
    return assignments.filter(isRecord).map((assignment) => ({
      slotKey: getString(assignment, 'slot_key') ?? getString(assignment, 'slotKey'),
      role: getString(assignment, 'role') ?? '',
      workerId: getString(assignment, 'worker_id') ?? getString(assignment, 'workerId'),
      workerName: getString(assignment, 'worker_name') ?? getString(assignment, 'workerName') ?? '',
    }));
  }

  const workers = getArray(item, 'workers');

  if (workers) {
    return workers.filter(isRecord).map((worker) => ({
      role: getString(worker, 'role') ?? '',
      workerId: getString(worker, 'worker_id') ?? getString(worker, 'workerId'),
      workerName:
        getString(worker, 'name') ??
        getString(worker, 'worker_name') ??
        getString(worker, 'workerName') ??
        '',
    }));
  }

  return roleLabels
    .map(([key, role]) => ({
      role,
      workerName: getString(item, key),
    }))
    .filter((assignment) => Boolean(assignment.workerName));
};

const normalizeSongs = (songs?: unknown[]): ScheduleSong[] => {
  if (!songs) {
    return [];
  }

  return songs
    .map((song) => {
      if (typeof song === 'string') {
        return { title: song };
      }

      if (!isRecord(song)) {
        return null;
      }

      const title = getString(song, 'title') ?? getString(song, 'name');

      if (!title) {
        return null;
      }

      return {
        songId: getString(song, 'song_id') ?? getString(song, 'songId'),
        title,
        artist: getString(song, 'artist'),
        key: getString(song, 'key'),
      };
    })
    .filter((song): song is ScheduleSong => Boolean(song));
};

const normalizeWorkerRoles = (roles?: unknown[]): WorkerRole[] => {
  const validRoles: WorkerRole[] = [
    'Leader',
    'Backup',
    'Acoustic',
    'Bass',
    'Drums',
    'Beatbox',
    'Keyboard',
    'Electric',
  ];

  return (roles ?? []).filter(
    (role): role is WorkerRole => typeof role === 'string' && validRoles.includes(role as WorkerRole),
  );
};

const toDateInputValue = (value: string | Date) => {
  if (typeof value === 'string') {
    const dateOnlyMatch = value.match(/^(\d{4})-(\d{2})-(\d{2})/);

    if (dateOnlyMatch) {
      return dateOnlyMatch[0];
    }
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return String(value);
  }

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;
};

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null;
};

const getString = (record: Record<string, unknown>, key: string) => {
  const value = record[key];
  return typeof value === 'string' ? value : undefined;
};

const getArray = (record: Record<string, unknown>, key: string) => {
  const value = record[key];
  return Array.isArray(value) ? value : undefined;
};
