import { FormEvent, useMemo, useState } from 'react';
import { FaTimes } from 'react-icons/fa';
import {
  AutoGeneratedScheduleRow,
  AutoGenerationPreview,
  AssignmentConstraint,
  confirmAutoGeneration,
  fetchAssignmentConstraints,
  getScheduleRequestConflicts,
  previewAutoGeneration,
} from '../../services/schedules';
import { Worker } from '../../models/Worker';
import { ServiceTypeConfiguration, WorkerGroup } from '../../models/ServiceConfiguration';
import EditableScheduleTable from './EditableScheduleTable';
import {
  isScheduleRowSaveable,
  withConstraintConflicts,
} from './scheduleAssignmentTable';

interface Props {
  monthDate: Date;
  workers: Worker[];
  serviceTypes: ServiceTypeConfiguration[];
  workerGroups: WorkerGroup[];
  onClose: () => void;
  onConfirmed: () => Promise<void> | void;
}

const AutoGenerateScheduleModal = ({ monthDate, workers, serviceTypes, workerGroups, onClose, onConfirmed }: Props) => {
  const [includeOptionalRoles, setIncludeOptionalRoles] = useState(true);
  const [allowYouthBackupFallback, setAllowYouthBackupFallback] = useState(true);
  const availableServiceTypes = serviceTypes.filter(
    (item) => item.is_active && item.auto_generation_enabled && item.recurrence.type === 'weekly',
  );
  const [serviceType, setServiceType] = useState(
    availableServiceTypes[0]?.code ?? '',
  );
  const [preview, setPreview] = useState<AutoGenerationPreview>();
  const [editableRows, setEditableRows] = useState<AutoGeneratedScheduleRow[]>([]);
  const [selectedDates, setSelectedDates] = useState<Set<string>>(new Set());
  const [error, setError] = useState('');
  const [saveSummary, setSaveSummary] = useState('');
  const [constraintsByDate, setConstraintsByDate] = useState<Record<string, AssignmentConstraint[]>>({});
  const [loadingPreview, setLoadingPreview] = useState(false);
  const [confirming, setConfirming] = useState(false);

  const year = monthDate.getFullYear();
  const month = monthDate.getMonth() + 1;
  const monthLabel = useMemo(() => {
    return new Intl.DateTimeFormat('en-US', {
      month: 'long',
      year: 'numeric',
    }).format(monthDate);
  }, [monthDate]);
  const serviceTypeConfig = availableServiceTypes.find((item) => item.code === serviceType);
  const weekdayLabel = serviceTypeConfig?.recurrence.weekday === undefined
    ? ''
    : weekdays[serviceTypeConfig.recurrence.weekday];
  const decorateRow = (row: AutoGeneratedScheduleRow) => withConstraintConflicts(
    row,
    constraintsByDate[row.date] ?? [],
  );
  const selectableRows = serviceTypeConfig
    ? editableRows.filter((row) => isScheduleRowSaveable(decorateRow(row), serviceTypeConfig))
    : [];
  const selectedRows = selectableRows.filter((row) => selectedDates.has(row.date));

  const handlePreview = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    setSaveSummary('');
    setLoadingPreview(true);

    try {
      const [result, constraints] = await Promise.all([
        previewAutoGeneration({
          year,
          month,
          service_type: serviceType,
          includeOptionalRoles,
          allowYouthBackupFallback,
        }),
        fetchAssignmentConstraints(year, month),
      ]);
      const nextConstraints = Object.fromEntries(
        constraints.dates.map((item) => [item.date, item.blocked_workers]),
      );
      setConstraintsByDate(nextConstraints);
      setPreview(result);
      setEditableRows(result.rows);
      setSelectedDates(
        new Set(
          result.rows
            .filter((row) => serviceTypeConfig && isScheduleRowSaveable(
              withConstraintConflicts(row, nextConstraints[row.date] ?? []),
              serviceTypeConfig,
            ))
            .map((row) => row.date),
        ),
      );
    } catch {
      setError('Auto-generation preview could not be created.');
    } finally {
      setLoadingPreview(false);
    }
  };

  const handleConfirm = async () => {
    setError('');
    setSaveSummary('');

    if (!selectedRows.length) {
      setError('No selected schedules are ready to save. Resolve the highlighted conflicts first.');
      return;
    }

    setConfirming(true);

    try {
      const locallyBlockedDates = [...selectedDates].filter(
        (date) => !selectedRows.some((row) => row.date === date),
      );
      const result = await confirmAutoGeneration({
        schedules: selectedRows.map((row) => ({
          date: row.date,
          service_type: row.service_type,
          assignments: row.assignments.map((assignment) => ({
            slot_key: assignment.slot_key,
            role: assignment.role,
            worker_id: assignment.worker_id,
          })),
        })),
      });
      const resultsByDate = new Map(result.items.map((item) => [item.date, item]));
      setEditableRows((current) => current.map((row) => {
        const item = resultsByDate.get(row.date);
        if (!item) return row;
        return item.status === 'created'
          ? { ...row, save_status: 'saved', conflicts: [] }
          : { ...row, conflicts: item.conflicts ?? [{
              code: 'INVALID_ASSIGNMENT',
              date: row.date,
              message: item.message ?? 'Schedule could not be saved',
            }] };
      }));
      setSelectedDates(new Set(
        [
          ...locallyBlockedDates,
          ...result.items
            .filter((item) => item.status === 'failed')
            .map((item) => item.date),
        ],
      ));
      let refreshed = true;
      try {
        await onConfirmed();
        const refreshedConstraints = await fetchAssignmentConstraints(year, month);
        setConstraintsByDate(Object.fromEntries(
          refreshedConstraints.dates.map((item) => [item.date, item.blocked_workers]),
        ));
      } catch {
        refreshed = false;
        setError('Schedules were saved, but the calendar could not be refreshed. Reload the page to see the latest assignments.');
      }

      const needsAttention = result.summary.failed + locallyBlockedDates.length;
      if (needsAttention === 0 && refreshed) {
        onClose();
        return;
      }

      setSaveSummary(
        `${result.summary.created} schedule${result.summary.created === 1 ? '' : 's'} saved. ${needsAttention} need${needsAttention === 1 ? 's' : ''} attention.`,
      );
    } catch (requestError) {
      setEditableRows((current) => current.map((row) =>
        selectedDates.has(row.date)
          ? { ...row, conflicts: getScheduleRequestConflicts(requestError, row.date) }
          : row,
      ));
      setError('Generated schedules could not be saved. Review the highlighted rows and try again.');
    } finally {
      setConfirming(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-950/50 px-4 py-4 sm:items-center sm:py-6">
      <section className="flex max-h-[calc(100dvh-2rem)] w-full min-w-0 max-w-[1500px] flex-col overflow-hidden rounded-lg bg-white shadow-xl sm:max-h-[calc(100dvh-3rem)]">
        <div className="flex shrink-0 items-start justify-between gap-4 border-b border-slate-200 p-4 sm:p-5">
          <div className="min-w-0">
            <p className="text-sm font-semibold uppercase tracking-wide text-amber-700">
              Auto generate
            </p>
            <h2 className="mt-1 text-xl font-bold text-slate-950">
              {serviceTypeConfig?.name ?? 'Service'} schedules for {monthLabel}
            </h2>
            <p className="mt-1 text-sm text-slate-600">
              Preview every {weekdayLabel} first, then save the generated schedules you approve.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 hover:bg-slate-100 hover:text-slate-950"
            aria-label="Close auto-generation"
          >
            <FaTimes />
          </button>
        </div>

        <div className="min-w-0 space-y-5 overflow-y-auto p-4 sm:p-5">
          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">
              {error}
            </div>
          )}
          {saveSummary && (
            <div className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm font-medium text-amber-800">
              {saveSummary}
            </div>
          )}

          <form
            onSubmit={handlePreview}
            className={`grid min-w-0 grid-cols-1 items-end gap-5 rounded-md border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 xl:gap-6 ${
              serviceType === 'main'
                ? 'xl:grid-cols-[160px_minmax(240px,320px)_minmax(190px,1fr)_minmax(190px,1fr)_145px]'
                : 'xl:grid-cols-[160px_minmax(240px,360px)_1fr_145px]'
            }`}
          >
              <div>
                <p className="text-xs font-bold uppercase text-slate-500">Month</p>
                <p className="mt-1 flex h-10 items-center text-sm font-bold text-slate-950">
                  {monthLabel}
                </p>
              </div>
              <label className="block min-w-0">
                <span className="text-xs font-bold uppercase text-slate-500">Service type</span>
                <select
                  value={serviceType}
                  onChange={(event) => {
                    setServiceType(event.target.value);
                    setPreview(undefined);
                    setEditableRows([]);
                    setSelectedDates(new Set());
                    setConstraintsByDate({});
                    setError('');
                    setSaveSummary('');
                  }}
                  className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-950 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100"
                >
                  {availableServiceTypes.map((option) => (
                    <option key={option._id} value={option.code}>
                      {option.name}
                    </option>
                  ))}
                </select>
              </label>
              <label className="flex min-h-10 items-center gap-2 text-sm font-semibold text-slate-700">
                <input
                  type="checkbox"
                  checked={includeOptionalRoles}
                  onChange={(event) => setIncludeOptionalRoles(event.target.checked)}
                  className="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500"
                />
                Include optional roles
              </label>
              {serviceType === 'main' && (
              <label className="flex min-h-10 items-center gap-2 text-sm font-semibold text-slate-700">
                <input
                  type="checkbox"
                  checked={allowYouthBackupFallback}
                  onChange={(event) => setAllowYouthBackupFallback(event.target.checked)}
                  className="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500"
                />
                Youth backup fallback
              </label>
              )}

            <button
              type="submit"
              disabled={loadingPreview}
              className={`col-span-1 inline-flex h-10 items-center justify-center rounded-md bg-slate-950 px-4 text-sm font-semibold text-white hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60 sm:col-span-2 xl:col-span-1 ${
                serviceType === 'main' ? '' : 'xl:col-start-4'
              }`}
            >
              {loadingPreview ? 'Generating...' : 'Generate preview'}
            </button>
          </form>

          {preview && serviceTypeConfig && (
            <EditableScheduleTable
              title="Preview"
              selectedLabel="generated schedule"
              saveLabel="Save selected"
              serviceType={serviceTypeConfig}
              rows={editableRows}
              workers={workers}
              workerGroups={workerGroups}
              selectedDates={selectedDates}
              saving={confirming}
              onRowsChange={setEditableRows}
              constraintsByDate={constraintsByDate}
              onSelectedDatesChange={setSelectedDates}
              onSave={handleConfirm}
            />
          )}
        </div>
      </section>
    </div>
  );
};

const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export default AutoGenerateScheduleModal;
