import { FormEvent, useMemo, useState } from 'react';
import { FaCheck, FaTimes } from 'react-icons/fa';
import {
  AutoGeneratedScheduleRow,
  AutoGenerationPreview,
  confirmAutoGeneration,
  previewAutoGeneration,
} from '../../services/schedules';
import { Worker, WorkerRole } from '../../models/Worker';

interface Props {
  monthDate: Date;
  workers: Worker[];
  onClose: () => void;
  onConfirmed: () => void;
}

const columns: Array<{ label: string; role: WorkerRole }> = [
  { label: 'Leader', role: 'Leader' },
  { label: 'Backup', role: 'Backup' },
  { label: 'Acoustic', role: 'Acoustic' },
  { label: 'Electric', role: 'Electric' },
  { label: 'Bass', role: 'Bass' },
  { label: 'Keyboard', role: 'Keyboard' },
  { label: 'Drums', role: 'Drums' },
];

const requiredRoles: WorkerRole[] = ['Leader', 'Acoustic', 'Bass', 'Drums'];

const AutoGenerateScheduleModal = ({ monthDate, workers, onClose, onConfirmed }: Props) => {
  const [includeOptionalRoles, setIncludeOptionalRoles] = useState(true);
  const [allowYouthBackupFallback, setAllowYouthBackupFallback] = useState(true);
  const [preview, setPreview] = useState<AutoGenerationPreview>();
  const [editableRows, setEditableRows] = useState<AutoGeneratedScheduleRow[]>([]);
  const [selectedDates, setSelectedDates] = useState<Set<string>>(new Set());
  const [error, setError] = useState('');
  const [loadingPreview, setLoadingPreview] = useState(false);
  const [confirming, setConfirming] = useState(false);

  const year = monthDate.getFullYear();
  const month = monthDate.getMonth() + 1;
  const monthLabel = useMemo(() => {
    return new Intl.DateTimeFormat('en-US', {
      month: 'long',
      year: 'numeric',
    }).format(monthDate);
  }, [monthDate]);

  const workersByRole = useMemo(() => {
    return columns.reduce<Record<string, Worker[]>>((acc, column) => {
      acc[column.role] = workers
        .filter((worker) => {
          return worker.status === 'active' && worker.roles.includes(column.role);
        })
        .sort((a, b) => a.name.localeCompare(b.name));
      return acc;
    }, {});
  }, [workers]);
  const selectableRows = editableRows.filter(isRowSaveable);
  const selectedRows = selectableRows.filter((row) => selectedDates.has(row.date));

  const handlePreview = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    setLoadingPreview(true);

    try {
      const result = await previewAutoGeneration({
        year,
        month,
        includeOptionalRoles,
        allowYouthBackupFallback,
      });
      setPreview(result);
      setEditableRows(result.rows);
      setSelectedDates(
        new Set(
          result.rows.filter(isRowSaveable).map((row) => row.date),
        ),
      );
    } catch {
      setError('Auto-generation preview could not be created.');
    } finally {
      setLoadingPreview(false);
    }
  };

  const handleConfirm = async () => {
    setError('');

    const invalidSelectedRow = selectedRows.find((row) => !isRowSaveable(row));

    if (invalidSelectedRow) {
      setError(`${invalidSelectedRow.date} still needs attention before saving.`);
      return;
    }

    setConfirming(true);

    try {
      await confirmAutoGeneration({
        schedules: selectedRows.map((row) => ({
          date: row.date,
          assignments: row.assignments.map((assignment) => ({
            role: assignment.role,
            worker_id: assignment.worker_id,
          })),
        })),
      });
      await onConfirmed();
      onClose();
    } catch {
      setError('Generated schedules could not be saved. Review conflicts and try again.');
    } finally {
      setConfirming(false);
    }
  };

  const toggleRow = (row: AutoGeneratedScheduleRow) => {
    if (!isRowSaveable(row)) {
      return;
    }

    setSelectedDates((current) => {
      const next = new Set(current);

      if (next.has(row.date)) {
        next.delete(row.date);
      } else {
        next.add(row.date);
      }

      return next;
    });
  };

  const handleAssignmentChange = (
    row: AutoGeneratedScheduleRow,
    role: WorkerRole,
    workerId: string,
  ) => {
    const worker = workers.find((item) => item._id === workerId);

    setEditableRows((currentRows) => {
      return currentRows.map((currentRow) => {
        if (currentRow.date !== row.date) {
          return currentRow;
        }

        const otherAssignments = currentRow.assignments.filter((assignment) => {
          return assignment.role !== role;
        });

        if (!worker) {
          return {
            ...currentRow,
            assignments: otherAssignments,
          };
        }

        return {
          ...currentRow,
          assignments: [
            ...otherAssignments,
            {
              role,
              worker_id: worker._id,
              worker_name: worker.name,
            },
          ].sort((a, b) => {
            return getColumnIndex(a.role) - getColumnIndex(b.role);
          }),
        };
      });
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 px-4 py-6">
      <section className="max-h-full w-full max-w-6xl overflow-auto rounded-lg bg-white shadow-xl">
        <div className="flex items-start justify-between gap-4 border-b border-slate-200 p-5">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wide text-amber-700">
              Auto generate
            </p>
            <h2 className="mt-1 text-xl font-bold text-slate-950">
              Main service schedules for {monthLabel}
            </h2>
            <p className="mt-1 text-sm text-slate-600">
              Preview every Sunday first, then save the generated schedules you approve.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 hover:bg-slate-100 hover:text-slate-950"
            aria-label="Close auto-generation"
          >
            <FaTimes />
          </button>
        </div>

        <div className="space-y-5 p-5">
          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">
              {error}
            </div>
          )}

          <form
            onSubmit={handlePreview}
            className="grid gap-3 rounded-md border border-slate-200 bg-slate-50 p-4 md:grid-cols-[1fr_auto]"
          >
            <div className="grid gap-3 sm:grid-cols-3">
              <div>
                <p className="text-xs font-bold uppercase text-slate-500">Month</p>
                <p className="mt-1 text-sm font-bold text-slate-950">{monthLabel}</p>
              </div>
              <label className="flex items-center gap-2 text-sm font-semibold text-slate-700">
                <input
                  type="checkbox"
                  checked={includeOptionalRoles}
                  onChange={(event) => setIncludeOptionalRoles(event.target.checked)}
                  className="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500"
                />
                Include optional roles
              </label>
              <label className="flex items-center gap-2 text-sm font-semibold text-slate-700">
                <input
                  type="checkbox"
                  checked={allowYouthBackupFallback}
                  onChange={(event) => setAllowYouthBackupFallback(event.target.checked)}
                  className="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500"
                />
                Youth backup fallback
              </label>
            </div>

            <button
              type="submit"
              disabled={loadingPreview}
              className="inline-flex items-center justify-center rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loadingPreview ? 'Generating...' : 'Generate preview'}
            </button>
          </form>

          {preview && (
            <div className="overflow-hidden rounded-md border border-slate-200">
              <div className="flex flex-col gap-2 border-b border-slate-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-sm font-bold text-slate-950">Preview</p>
                  <p className="text-xs font-semibold text-slate-500">
                    {selectedRows.length} generated schedule
                    {selectedRows.length === 1 ? '' : 's'} selected
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleConfirm}
                  disabled={!selectedRows.length || confirming}
                  className="inline-flex items-center justify-center gap-2 rounded-md bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <FaCheck />
                  {confirming ? 'Saving...' : 'Save selected'}
                </button>
              </div>

              <div className="overflow-x-auto">
                <table className="min-w-full table-fixed border-collapse text-sm">
                  <thead className="border-b border-slate-200 bg-amber-50 text-xs font-bold uppercase text-slate-600">
                    <tr>
                      <th className="w-14 px-3 py-3 text-left">Save</th>
                      <th className="w-32 px-3 py-3 text-left">Date</th>
                      <th className="w-36 px-3 py-3 text-left">Status</th>
                      {columns.map((column) => (
                        <th key={column.role} className="px-3 py-3 text-left">
                          {column.label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {editableRows.map((row) => {
                      const rowWarnings = getRowWarnings(row);
                      const rowStatus = getDisplayStatus(row);

                      return (
                      <tr key={row.date} className="align-top">
                        <td className="px-3 py-3">
                          <input
                            type="checkbox"
                            checked={selectedDates.has(row.date)}
                            disabled={!isRowSaveable(row)}
                            onChange={() => toggleRow(row)}
                            className="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500 disabled:opacity-40"
                            aria-label={`Save generated schedule for ${row.date}`}
                          />
                        </td>
                        <td className="px-3 py-3 font-bold text-slate-950">
                          {formatPreviewDate(row.date)}
                        </td>
                        <td className="px-3 py-3">
                          <span
                            className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${getStatusClassName(rowStatus)}`}
                          >
                            {rowStatus.replace('_', ' ')}
                          </span>
                          {rowWarnings.length > 0 && (
                            <div className="mt-2 space-y-1">
                              {rowWarnings.map((warning) => (
                                <p key={warning} className="text-xs font-semibold text-red-700">
                                  {warning}
                                </p>
                              ))}
                            </div>
                          )}
                        </td>
                        {columns.map((column) => (
                          <td key={column.role} className="px-3 py-3">
                            {row.status === 'skipped' ? (
                              <span className="font-semibold text-slate-950">
                                {getWorkerForRole(row, column.role) || '-'}
                              </span>
                            ) : (
                              <select
                                value={getWorkerIdForRole(row, column.role)}
                                onChange={(event) =>
                                  handleAssignmentChange(row, column.role, event.target.value)
                                }
                                className="w-full min-w-36 rounded-md border border-slate-300 px-2 py-1 text-sm font-semibold text-slate-950 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100"
                                aria-label={`${column.label} for ${row.date}`}
                              >
                                <option value="">-</option>
                                {(workersByRole[column.role] ?? []).map((worker) => (
                                  <option key={worker._id} value={worker._id}>
                                    {worker.name}
                                  </option>
                                ))}
                              </select>
                            )}
                          </td>
                        ))}
                      </tr>
                    );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </section>
    </div>
  );
};

const getWorkerForRole = (row: AutoGeneratedScheduleRow, role: string) => {
  return row.assignments.find((assignment) => assignment.role === role)?.worker_name;
};

const getWorkerIdForRole = (row: AutoGeneratedScheduleRow, role: string) => {
  return row.assignments.find((assignment) => assignment.role === role)?.worker_id ?? '';
};

const getColumnIndex = (role: string) => {
  const index = columns.findIndex((column) => column.role === role);
  return index === -1 ? columns.length : index;
};

const getRowWarnings = (row: AutoGeneratedScheduleRow) => {
  if (row.status === 'skipped') {
    return row.warnings;
  }

  const warnings = requiredRoles
    .filter((role) => !getWorkerIdForRole(row, role))
    .map((role) => `Missing required role: ${role}`);
  const workerIds = row.assignments
    .map((assignment) => assignment.worker_id)
    .filter(Boolean);
  const uniqueWorkerIds = new Set(workerIds);

  if (uniqueWorkerIds.size !== workerIds.length) {
    warnings.push('A worker cannot be assigned to multiple roles.');
  }

  return warnings;
};

const getDisplayStatus = (row: AutoGeneratedScheduleRow) => {
  if (row.status === 'skipped') {
    return row.status;
  }

  return getRowWarnings(row).length ? 'needs_attention' : 'generated';
};

const isRowSaveable = (row: AutoGeneratedScheduleRow) => {
  return row.status !== 'skipped' && getRowWarnings(row).length === 0;
};

const formatPreviewDate = (dateValue: string) => {
  const [year, month, day] = dateValue.split('-').map(Number);

  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
  }).format(new Date(year, month - 1, day));
};

const getStatusClassName = (status: AutoGeneratedScheduleRow['status']) => {
  if (status === 'generated') {
    return 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200';
  }

  if (status === 'skipped') {
    return 'bg-slate-100 text-slate-600 ring-1 ring-slate-200';
  }

  return 'bg-red-50 text-red-700 ring-1 ring-red-200';
};

export default AutoGenerateScheduleModal;
