import { useEffect, useMemo, useState } from 'react';
import { FaTimes } from 'react-icons/fa';
import { WorshipSchedule } from '../../models/Schedule';
import { Worker } from '../../models/Worker';
import { ServiceTypeConfiguration, WorkerGroup } from '../../models/ServiceConfiguration';
import {
  AutoGeneratedScheduleRow,
  AssignmentConstraint,
  fetchAssignmentConstraints,
  getScheduleRequestConflicts,
  updateSchedule,
} from '../../services/schedules';
import EditableScheduleTable from './EditableScheduleTable';
import {
  isScheduleRowSaveable,
  withConstraintConflicts,
} from './scheduleAssignmentTable';

interface Props {
  monthDate: Date;
  serviceType: ServiceTypeConfiguration;
  schedules: WorshipSchedule[];
  workers: Worker[];
  workerGroups: WorkerGroup[];
  onClose: () => void;
  onSaved: () => Promise<void> | void;
}

const BulkEditSchedulesModal = ({
  monthDate,
  serviceType,
  schedules,
  workers,
  workerGroups,
  onClose,
  onSaved,
}: Props) => {
  const initialRows = useMemo(() => {
    return schedules.map(toEditableRow);
  }, [schedules]);
  const [rows, setRows] = useState<AutoGeneratedScheduleRow[]>(initialRows);
  const [selectedDates, setSelectedDates] = useState<Set<string>>(() => {
    return new Set(
      initialRows
        .filter((row) => isScheduleRowSaveable(row, serviceType))
        .map((row) => row.date),
    );
  });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [saveSummary, setSaveSummary] = useState('');
  const [constraintsByDate, setConstraintsByDate] = useState<Record<string, AssignmentConstraint[]>>({});
  const [constraintStatus, setConstraintStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const scheduleIdsByDate = useMemo(
    () => Object.fromEntries(schedules.map((schedule) => [schedule.date, schedule.id])),
    [schedules],
  );
  const monthLabel = useMemo(() => {
    return new Intl.DateTimeFormat('en-US', {
      month: 'long',
      year: 'numeric',
    }).format(monthDate);
  }, [monthDate]);

  useEffect(() => {
    setConstraintStatus('loading');
    fetchAssignmentConstraints(monthDate.getFullYear(), monthDate.getMonth() + 1)
      .then((result) => setConstraintsByDate(Object.fromEntries(
        result.dates.map((item) => [item.date, item.blocked_workers]),
      )))
      .then(() => setConstraintStatus('ready'))
      .catch(() => {
        setConstraintStatus('error');
        setError('Worker availability could not be loaded. Try reopening the monthly editor.');
      });
  }, [monthDate]);

  const handleSave = async () => {
    const selectedRows = rows.filter((row) => {
      const decorated = withConstraintConflicts(
        row,
        constraintsByDate[row.date] ?? [],
        scheduleIdsByDate[row.date],
      );
      return selectedDates.has(row.date) && isScheduleRowSaveable(decorated, serviceType);
    });

    if (!selectedRows.length) {
      setError('No selected schedules are ready to save. Resolve the highlighted conflicts first.');
      return;
    }

    setSaving(true);
    setError('');
    setSaveSummary('');

    try {
      const scheduleByDate = new Map(schedules.map((schedule) => [schedule.date, schedule]));
      const results = await Promise.allSettled(
        selectedRows.map((row) => {
          const schedule = scheduleByDate.get(row.date);

          if (!schedule) {
            return Promise.reject(new Error(`Schedule for ${row.date} was not found.`));
          }

          return updateSchedule(schedule.id, {
            assignments: row.assignments.map((assignment) => ({
              slot_key: assignment.slot_key,
              role: assignment.role,
              worker_id: assignment.worker_id,
            })),
          });
        }),
      );
      const failedDates = new Set<string>();
      const succeededDates = new Set<string>();
      const resultsByDate = new Map(
        selectedRows.map((row, index) => [row.date, results[index]]),
      );
      resultsByDate.forEach((result, date) => {
        (result.status === 'fulfilled' ? succeededDates : failedDates).add(date);
      });
      rows.forEach((row) => {
        if (selectedDates.has(row.date) && !selectedRows.some((item) => item.date === row.date)) {
          failedDates.add(row.date);
        }
      });

      setRows((current) => current.map((row) => {
        const result = resultsByDate.get(row.date);
        if (!result) return row;
        if (result.status === 'fulfilled') {
          return { ...toEditableRow(result.value), save_status: 'saved' };
        }
        return {
          ...row,
          conflicts: getScheduleRequestConflicts(result.reason, row.date),
        };
      }));
      setSelectedDates(failedDates);

      let refreshed = true;
      try {
        await onSaved();
        const refreshedConstraints = await fetchAssignmentConstraints(
          monthDate.getFullYear(),
          monthDate.getMonth() + 1,
        );
        setConstraintsByDate(Object.fromEntries(
          refreshedConstraints.dates.map((item) => [item.date, item.blocked_workers]),
        ));
      } catch {
        refreshed = false;
        setError('Schedules were saved, but the calendar could not be refreshed. Reload the page to see the latest assignments.');
      }

      if (failedDates.size > 0) {
        setSaveSummary(
          `${succeededDates.size} schedule${succeededDates.size === 1 ? '' : 's'} saved. ${failedDates.size} need${failedDates.size === 1 ? 's' : ''} attention.`,
        );
        return;
      }

      if (refreshed) {
        onClose();
      }
    } catch {
      setError('Schedules could not be refreshed after saving. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 px-4 py-6">
      <section className="max-h-full w-full max-w-[1500px] overflow-auto rounded-lg bg-white shadow-xl">
        <div className="flex items-start justify-between gap-4 border-b border-slate-200 p-5">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wide text-amber-700">
              Bulk edit
            </p>
            <h2 className="mt-1 text-xl font-bold text-slate-950">
              {serviceType.name} schedules for {monthLabel}
            </h2>
            <p className="mt-1 text-sm text-slate-600">
              Adjust worker assignments across the month, then save the selected schedules.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 w-9 items-center justify-center rounded-md text-slate-500 hover:bg-slate-100 hover:text-slate-950"
            aria-label="Close bulk editor"
          >
            <FaTimes aria-hidden="true" />
          </button>
        </div>

        <div className="space-y-4 p-5">
          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">
              {error}
            </div>
          )}
          {saveSummary && (
            <div className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm font-medium text-amber-800">
              {saveSummary}
            </div>
          )}

          {constraintStatus === 'loading' && (
            <p className="rounded-md border border-slate-200 bg-slate-50 px-4 py-8 text-center text-sm font-semibold text-slate-600">
              Checking worker availability...
            </p>
          )}
          {constraintStatus === 'ready' && <EditableScheduleTable
            title="Monthly schedules"
            selectedLabel="schedule"
            saveLabel="Save selected"
            serviceType={serviceType}
            rows={rows}
            workers={workers}
            workerGroups={workerGroups}
            selectedDates={selectedDates}
            saving={saving}
            constraintsByDate={constraintsByDate}
            scheduleIdsByDate={scheduleIdsByDate}
            mode="bulk-edit"
            onRowsChange={setRows}
            onSelectedDatesChange={setSelectedDates}
            onSave={handleSave}
          />}
        </div>
      </section>
    </div>
  );
};

const toEditableRow = (schedule: WorshipSchedule): AutoGeneratedScheduleRow => {
  return {
    date: schedule.date,
    service_type: schedule.serviceType,
    status: 'generated',
    assignments: schedule.assignments
      .filter((assignment) => assignment.workerId)
      .map((assignment) => ({
        role: assignment.role,
        slot_key: assignment.slotKey,
        worker_id: assignment.workerId as string,
        worker_name: assignment.workerName,
      })),
    warnings: [],
  };
};

export default BulkEditSchedulesModal;
