import { FaCheck } from 'react-icons/fa';
import {
  ServiceTypeConfiguration,
  WorkerGroup,
} from '../../models/ServiceConfiguration';
import { Worker, WorkerRole } from '../../models/Worker';
import {
  AssignmentConstraint,
  AutoGeneratedScheduleRow,
} from '../../services/schedules';
import {
  getSlotEligibility,
  isWorkerEligible,
} from '../../utils/serviceRules';
import {
  getScheduleAssignmentColumns,
  getScheduleRowWarnings,
  getApplicableConstraints,
  isScheduleRowSaveable,
  ScheduleAssignmentColumn,
  withConstraintConflicts,
} from './scheduleAssignmentTable';

interface Props {
  title: string;
  selectedLabel: string;
  saveLabel: string;
  serviceType: ServiceTypeConfiguration;
  rows: AutoGeneratedScheduleRow[];
  workers: Worker[];
  workerGroups: WorkerGroup[];
  selectedDates: Set<string>;
  saving: boolean;
  constraintsByDate?: Record<string, AssignmentConstraint[]>;
  scheduleIdsByDate?: Record<string, string>;
  mode?: 'generation' | 'bulk-edit';
  onRowsChange: (rows: AutoGeneratedScheduleRow[]) => void;
  onSelectedDatesChange: (dates: Set<string>) => void;
  onSave: () => void;
}

const EditableScheduleTable = ({
  title,
  selectedLabel,
  saveLabel,
  serviceType,
  rows,
  workers,
  workerGroups,
  selectedDates,
  saving,
  constraintsByDate = {},
  scheduleIdsByDate = {},
  mode = 'generation',
  onRowsChange,
  onSelectedDatesChange,
  onSave,
}: Props) => {
  const columns = getScheduleAssignmentColumns(serviceType);
  const decorateRow = (row: AutoGeneratedScheduleRow) => withConstraintConflicts(
    row,
    constraintsByDate[row.date] ?? [],
    scheduleIdsByDate[row.date],
  );
  const selectedRows = rows.filter(
    (row) =>
      selectedDates.has(row.date) &&
      isScheduleRowSaveable(decorateRow(row), serviceType),
  );
  const selectedCount = rows.filter((row) => selectedDates.has(row.date)).length;

  const toggleRow = (row: AutoGeneratedScheduleRow) => {
    const isSelected = selectedDates.has(row.date);
    if (!isSelected && !isScheduleRowSaveable(decorateRow(row), serviceType)) {
      return;
    }

    const next = new Set(selectedDates);
    next.has(row.date) ? next.delete(row.date) : next.add(row.date);
    onSelectedDatesChange(next);
  };

  const handleAssignmentChange = (
    row: AutoGeneratedScheduleRow,
    column: ScheduleAssignmentColumn,
    selections: string[],
  ) => {
    const selectedAssignments = selections.flatMap((selection) => {
      const [role, workerId] = selection.split(':') as [WorkerRole, string];
      const worker = workers.find((item) => item._id === workerId);
      return worker
        ? [{
            slot_key: column.key,
            role,
            worker_id: worker._id,
            worker_name: worker.name,
          }]
        : [];
    });

    onRowsChange(
      rows.map((currentRow) => {
        if (currentRow.date !== row.date) {
          return currentRow;
        }

        const otherAssignments = currentRow.assignments.filter(
          (assignment) => assignment.slot_key !== column.key,
        );

        return {
          ...currentRow,
          conflicts: [],
          save_status: undefined,
          assignments: [...otherAssignments, ...selectedAssignments].sort(
            (a, b) =>
              getColumnIndex(a.slot_key, columns) -
              getColumnIndex(b.slot_key, columns),
          ),
        };
      }),
    );
  };

  return (
    <div className="overflow-hidden rounded-md border border-slate-200">
      <div className="flex flex-col gap-2 border-b border-slate-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-bold text-slate-950">{title}</p>
          <p className="text-xs font-semibold text-slate-500">
            {selectedCount} {selectedLabel}{selectedCount === 1 ? '' : 's'} selected
            {selectedCount !== selectedRows.length
              ? ` · ${selectedRows.length} ready to save`
              : ''}
          </p>
        </div>
        <button
          type="button"
          onClick={onSave}
          disabled={!selectedRows.length || saving}
          className="inline-flex items-center justify-center gap-2 rounded-md bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700 disabled:opacity-60"
        >
          <FaCheck />
          {saving ? 'Saving...' : saveLabel}
        </button>
      </div>

      <div className="overflow-x-auto">
        <table
          className="table-fixed border-collapse text-sm"
          style={{ minWidth: `${420 + columns.length * 170}px` }}
        >
          <thead className="border-b border-slate-200 bg-amber-50 text-xs font-bold uppercase text-slate-600">
            <tr>
              <th className="w-14 px-3 py-3 text-left">Save</th>
              <th className="w-28 px-3 py-3 text-left">Date</th>
              <th className="w-56 px-3 py-3 text-left">Status</th>
              {columns.map((column) => (
                <th key={column.key} className="w-40 px-3 py-3 text-left">
                  {column.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {rows.map((row) => {
              const decoratedRow = decorateRow(row);
              const warnings = getScheduleRowWarnings(decoratedRow, serviceType);
              const status =
                row.save_status === 'saved'
                  ? 'saved'
                  : row.status === 'skipped'
                  ? 'skipped'
                  : warnings.length
                    ? 'needs_attention'
                    : mode === 'bulk-edit'
                      ? 'ready'
                      : 'generated';

              return (
                <tr key={row.date} className="align-top">
                  <td className="px-3 py-3">
                    <input
                      type="checkbox"
                      checked={selectedDates.has(row.date)}
                      disabled={
                        row.status === 'skipped' ||
                        row.save_status === 'saved' ||
                        (!selectedDates.has(row.date) &&
                          !isScheduleRowSaveable(decoratedRow, serviceType))
                      }
                      onChange={() => toggleRow(row)}
                      className="h-4 w-4 accent-amber-600 disabled:opacity-40"
                    />
                  </td>
                  <td className="px-3 py-3 font-bold text-slate-950">
                    {formatTableDate(row.date)}
                  </td>
                  <td className="px-3 py-3">
                    <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold uppercase ${getStatusClassName(status)}`}>
                      {status.replace('_', ' ')}
                    </span>
                    {warnings.map((warning) => (
                      <p key={warning} className="mt-2 text-xs font-semibold leading-4 text-red-700">
                        {warning}
                      </p>
                    ))}
                  </td>
                  {columns.map((column) => {
                    const assignments = row.assignments.filter(
                      (item) =>
                        item.slot_key === column.key ||
                        (!item.slot_key &&
                          column.allowed_roles.includes(
                            item.role as WorkerRole,
                          )),
                    );
                    const eligibility = getSlotEligibility(
                      column,
                      serviceType.worker_eligibility,
                    );
                    const options = workers
                      .filter(
                        (worker) =>
                          worker.status === 'active' &&
                          column.allowed_roles.some((role) =>
                            worker.roles.includes(role),
                          ) &&
                          isWorkerEligible(worker, eligibility, workerGroups),
                      )
                      .flatMap((worker) =>
                        column.allowed_roles
                          .filter((role) => worker.roles.includes(role))
                          .map((role) => ({ worker, role })),
                      );
                    const applicableConstraints = getApplicableConstraints(
                      constraintsByDate[row.date] ?? [],
                      scheduleIdsByDate[row.date],
                    );
                    const blockedWorkerIds = new Set(
                      applicableConstraints.map((constraint) => constraint.worker_id),
                    );
                    const visibleOptions = options.filter(
                      ({ worker }) => !blockedWorkerIds.has(worker._id),
                    );
                    const selectedBlockedAssignments = assignments.filter(
                      (assignment) => blockedWorkerIds.has(assignment.worker_id),
                    );
                    const hiddenWorkerCount = new Set(
                      options
                        .filter(({ worker }) => blockedWorkerIds.has(worker._id))
                        .map(({ worker }) => worker._id),
                    ).size;
                    const hasColumnConflict = decoratedRow.conflicts?.some(
                      (conflict) =>
                        conflict.slot_key === column.key ||
                        assignments.some(
                          (assignment) => assignment.worker_id === conflict.worker_id,
                        ),
                    );

                    return (
                      <td
                        key={column.key}
                        className={`px-3 py-3 ${hasColumnConflict ? 'bg-red-50' : ''}`}
                      >
                        {row.status === 'skipped' || row.save_status === 'saved' ? (
                          <span className="font-semibold text-slate-950">
                            {assignments.map((assignment) => assignment.worker_name).join(', ') || '-'}
                          </span>
                        ) : (
                          <select
                            multiple={Boolean(column.allow_multiple)}
                            size={column.allow_multiple ? 4 : undefined}
                            value={assignments.map(
                              (assignment) => `${assignment.role}:${assignment.worker_id}`,
                            )}
                            onChange={(event) =>
                              handleAssignmentChange(
                                row,
                                column,
                                Array.from(event.target.selectedOptions, (option) => option.value),
                              )
                            }
                            className={`w-full min-w-36 rounded-md border px-2 py-1 text-sm font-semibold outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100 ${hasColumnConflict ? 'border-red-400 bg-red-50' : 'border-slate-300'}`}
                          >
                            {!column.allow_multiple && <option value="">-</option>}
                            {selectedBlockedAssignments.map((assignment) => {
                              const constraint = applicableConstraints.find(
                                (item) => item.worker_id === assignment.worker_id,
                              );
                              return (
                                <option
                                  key={`blocked-${assignment.role}-${assignment.worker_id}`}
                                  value={`${assignment.role}:${assignment.worker_id}`}
                                  disabled
                                >
                                  {assignment.worker_name} — {constraint?.code === 'WORKER_UNAVAILABLE' ? 'unavailable' : 'already scheduled'}
                                </option>
                              );
                            })}
                            {visibleOptions.map(({ worker, role }) => (
                              <option
                                key={`${role}-${worker._id}`}
                                value={`${role}:${worker._id}`}
                              >
                                {worker.name}
                                {column.allowed_roles.length > 1
                                  ? ` (${role})`
                                  : ''}
                              </option>
                            ))}
                          </select>
                        )}
                        {row.status !== 'skipped' && row.save_status !== 'saved' && selectedBlockedAssignments.map((assignment) => (
                          <button
                            key={`remove-${assignment.role}-${assignment.worker_id}`}
                            type="button"
                            onClick={() => handleAssignmentChange(
                              row,
                              column,
                              assignments
                                .filter((item) =>
                                  item.worker_id !== assignment.worker_id ||
                                  item.role !== assignment.role,
                                )
                                .map((item) => `${item.role}:${item.worker_id}`),
                            )}
                            className="mt-1 block text-left text-xs font-bold text-red-700 hover:text-red-900"
                          >
                            Remove {assignment.worker_name}
                          </button>
                        ))}
                        {hiddenWorkerCount > 0 && row.status !== 'skipped' && row.save_status !== 'saved' && (
                          <p className="mt-1 text-xs font-semibold text-slate-500">
                            {hiddenWorkerCount} unavailable or already scheduled worker{hiddenWorkerCount === 1 ? '' : 's'} hidden
                          </p>
                        )}
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const getColumnIndex = (
  slotKey: string | undefined,
  columns: ScheduleAssignmentColumn[],
) => {
  const index = columns.findIndex((column) => column.key === slotKey);
  return index < 0 ? columns.length : index;
};

const formatTableDate = (dateValue: string) => {
  const [year, month, day] = dateValue.split('-').map(Number);
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
  }).format(new Date(year, month - 1, day));
};

const getStatusClassName = (status: string) => {
  if (status === 'generated' || status === 'ready' || status === 'saved') {
    return 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200';
  }
  if (status === 'skipped') {
    return 'bg-slate-100 text-slate-600 ring-1 ring-slate-200';
  }
  return 'bg-red-50 text-red-700 ring-1 ring-red-200';
};

export default EditableScheduleTable;
