import {
  AssignmentSlot,
  ServiceTypeConfiguration,
} from '../../models/ServiceConfiguration';
import { WorkerRole } from '../../models/Worker';
import { AutoGeneratedScheduleRow } from '../../services/schedules';

export type ScheduleAssignmentColumn = AssignmentSlot;

export const getScheduleAssignmentColumns = (
  serviceType: ServiceTypeConfiguration,
) =>
  [...serviceType.assignment_slots].sort(
    (a, b) => a.display_order - b.display_order,
  );

export const getScheduleRowWarnings = (
  row: AutoGeneratedScheduleRow,
  serviceType: ServiceTypeConfiguration,
) => {
  if (row.status === 'skipped') {
    return row.warnings;
  }

  const warnings = getScheduleAssignmentColumns(serviceType)
    .filter(
      (slot) =>
        slot.required &&
        !row.assignments.some(
          (assignment) =>
            assignment.slot_key === slot.key ||
            (!assignment.slot_key &&
              slot.allowed_roles.includes(assignment.role as WorkerRole)),
        ),
    )
    .map((slot) => `Missing required assignment: ${slot.label}`);

  if (hasUnsupportedDuplicateWorker(row)) {
    warnings.push('A worker cannot be assigned to multiple unsupported roles.');
  }

  return warnings;
};

export const isScheduleRowSaveable = (
  row: AutoGeneratedScheduleRow,
  serviceType: ServiceTypeConfiguration,
) =>
  row.status !== 'skipped' &&
  getScheduleRowWarnings(row, serviceType).length === 0;

const hasUnsupportedDuplicateWorker = (row: AutoGeneratedScheduleRow) => {
  const rolesByWorker = row.assignments.reduce<Map<string, WorkerRole[]>>(
    (roles, assignment) => {
      const workerRoles = roles.get(assignment.worker_id) ?? [];
      workerRoles.push(assignment.role as WorkerRole);
      roles.set(assignment.worker_id, workerRoles);
      return roles;
    },
    new Map(),
  );

  return [...rolesByWorker.values()].some((roles) => {
    if (roles.length === 1) {
      return false;
    }

    const roleSet = new Set(roles);
    return !(
      roles.length === 2 &&
      roleSet.has('Acoustic') &&
      (roleSet.has('Leader') || roleSet.has('Backup'))
    );
  });
};
