import {
  AssignmentSlot,
  ServiceTypeConfiguration,
} from '../../models/ServiceConfiguration';
import { WorkerRole } from '../../models/Worker';
import {
  AssignmentConstraint,
  AutoGeneratedScheduleRow,
  ScheduleConflict,
} from '../../services/schedules';

export type ScheduleAssignmentColumn = AssignmentSlot;

export const getScheduleAssignmentColumns = (
  serviceType: ServiceTypeConfiguration,
) =>
  [...serviceType.assignment_slots].sort(
    (a, b) => a.display_order - b.display_order,
  );

export const getScheduleRowWarnings = (
  row: AutoGeneratedScheduleRow,
  serviceType: ServiceTypeConfiguration,
) => {
  if (row.status === 'skipped') {
    return row.warnings;
  }

  const warnings = getScheduleAssignmentColumns(serviceType)
    .filter(
      (slot) =>
        slot.required &&
        !row.assignments.some(
          (assignment) =>
            assignment.slot_key === slot.key ||
            (!assignment.slot_key &&
              slot.allowed_roles.includes(assignment.role as WorkerRole)),
        ),
    )
    .map((slot) => `Missing required assignment: ${slot.label}`);

  if (hasUnsupportedDuplicateWorker(row)) {
    warnings.push('A worker cannot be assigned to multiple unsupported roles.');
  }

  row.conflicts?.forEach((conflict) => {
    if (!warnings.includes(conflict.message)) {
      warnings.push(conflict.message);
    }
  });

  return warnings;
};

export const isScheduleRowSaveable = (
  row: AutoGeneratedScheduleRow,
  serviceType: ServiceTypeConfiguration,
) =>
  row.status !== 'skipped' &&
  row.save_status !== 'saved' &&
  getScheduleRowWarnings(row, serviceType).length === 0;

export const getApplicableConstraints = (
  constraints: AssignmentConstraint[],
  currentScheduleId?: string,
) => constraints.filter((constraint) => {
  return constraint.blocking_schedule?.id !== currentScheduleId;
});

export const getConstraintConflicts = (
  row: AutoGeneratedScheduleRow,
  constraints: AssignmentConstraint[],
  currentScheduleId?: string,
): ScheduleConflict[] => {
  if (row.save_status === 'saved') {
    return [];
  }

  const applicable = getApplicableConstraints(constraints, currentScheduleId);

  return row.assignments.flatMap((assignment) => {
    return applicable
      .filter((constraint) => constraint.worker_id === assignment.worker_id)
      .map((constraint) => ({
        ...constraint,
        date: row.date,
        worker_name: constraint.worker_name ?? assignment.worker_name,
        slot_key: assignment.slot_key,
        role: assignment.role,
        message: constraint.code === 'WORKER_UNAVAILABLE'
          ? `${assignment.worker_name} is unavailable on this date`
          : `${assignment.worker_name} is already assigned to ${constraint.blocking_schedule?.service_type ?? 'another service'}${constraint.blocking_schedule?.role ? ` as ${constraint.blocking_schedule.role}` : ''}`,
      }));
  });
};

export const withConstraintConflicts = (
  row: AutoGeneratedScheduleRow,
  constraints: AssignmentConstraint[],
  currentScheduleId?: string,
): AutoGeneratedScheduleRow => ({
  ...row,
  conflicts: [
    ...(row.conflicts ?? []),
    ...getConstraintConflicts(row, constraints, currentScheduleId),
  ].filter((conflict, index, all) => {
    return all.findIndex((candidate) =>
      candidate.code === conflict.code &&
      candidate.worker_id === conflict.worker_id &&
      candidate.slot_key === conflict.slot_key,
    ) === index;
  }),
});

const hasUnsupportedDuplicateWorker = (row: AutoGeneratedScheduleRow) => {
  const rolesByWorker = row.assignments.reduce<Map<string, WorkerRole[]>>(
    (roles, assignment) => {
      const workerRoles = roles.get(assignment.worker_id) ?? [];
      workerRoles.push(assignment.role as WorkerRole);
      roles.set(assignment.worker_id, workerRoles);
      return roles;
    },
    new Map(),
  );

  return [...rolesByWorker.values()].some((roles) => {
    if (roles.length === 1) {
      return false;
    }

    const roleSet = new Set(roles);
    return !(
      roles.length === 2 &&
      roleSet.has('Acoustic') &&
      (roleSet.has('Leader') || roleSet.has('Backup'))
    );
  });
};
